<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-0C21L1K2" failures="1" tests="1" name="Error(failed)" time="8.3" errors="0" timestamp="2023-04-16T19:04:55 IST">
  <testcase classname="TimeTracking.ActiTime.ErrorValidation" name="verifyLoginErrorMessage" time="3.26">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at TimeTracking.ActiTime.ErrorValidation.verifyLoginErrorMessage(ErrorValidation.java:17)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- verifyLoginErrorMessage -->
</testsuite> <!-- Error(failed) -->
